version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: DAXBNB
    ports:
      - "3308:3306" # Puerto de MySQL disponible en localhost:3308
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_daxbnb
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80" # Accede a phpMyAdmin en http://localhost:8080
    depends_on:
      - db

volumes:
  db_data: